name: Build Kernel

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
      id: go

    - name: Build
      env:
        CGO_ENABLED: 0
      run: |
        go build -o spitfire-build-kernel ./cmd/spitfire-build-kernel/main.go

    - name: Build Container Image
      run: echo hello
        #./spitfire-build-kernel -arch x86_64 -build-image       

    - name: Run Container and build kernel
      run: gzip -c /etc/hosts >> vmlinuz
        #./spitfire-build-kernel -arch x86_64 -run-container       
        
    - name: Upload kernel
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vmlinuz
        asset_name: vmliuz
        asset_content_type: application/octet-stream
