name: Build Kernel

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
      id: go

    - name: Build
      env:
        CGO_ENABLED: 0
      run: |
        go build -o spitfire-build-kernel ./cmd/spitfire-build-kernel/main.go
        file spitfire-build-kernel

    - name: Build Container Image
      run: |
        ./spitfire-build-kernel -arch x86_64 -build-image       

    - name: Run Container and build kernel
      run: |
        ./spitfire-build-kernel -arch x86_64 -run-container
        gzip -c /tmp/kernel.image/vmlinux >> vmlinuz
        
    - name: Upload kernel
      run: |
        git config user.name spitfire-kernel-builder && git config user.email kernelbuilder@spitfire.com
        git branch kernel && git switch kernel
        git add vmlinuz && git commit -m "update kernel build"
        git push -u origin kernel
