name: Build Kernel

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19
      id: go

    - name: Build
      run: |
        CGO_ENABLED=O go build -o spitfire-build-kernel ./cmd/spitfire-build-kernel/main.go

    - name: Build Container Image
      run: |
        ./spitfire-build-kernel -arch x86_64 -build-image
        file spitfire-build-kernel

    #- name: Run Container and build kernel
    #  run: |
    #    ./spitfire-build-kernel -arch x86_64 -run-container
